# Generated by Django 5.2.4 on 2025-07-31 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='intrucions',
            new_name='instructions',
        ),
    ]
